# generated by datamodel-codegen:
#   filename:  <dict>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class DownloaderOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    http_chunk_size: int


class Fragment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    duration: float


class Format(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asr: int | None = None
    filesize: int | None = None
    format_id: str
    format_note: str | None = None
    source_preference: int | None = None
    fps: float | None = None
    audio_channels: int | None = None
    height: int | None = None
    quality: float | None = None
    has_drm: bool | None = None
    tbr: float | None = None
    filesize_approx: int | None = None
    url: str
    width: int | None = None
    language: str | None = None
    language_preference: int | None = None
    preference: None = None
    ext: str
    vcodec: str
    acodec: str
    dynamic_range: None = None
    available_at: int | None = None
    downloader_options: DownloaderOptions | None = None
    container: str | None = None
    protocol: str | None = None
    rows: int | None = None
    columns: int | None = None
    fragments: list[Fragment] | None = None
    format_index: None = None
    manifest_url: str | None = None


class Thumbnail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    height: int | None = None
    width: int | None = None
    preference: int


class AbItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AfItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SqItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ArItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class A(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AzItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BhoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class B(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CebItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhHan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhHantItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class C(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DzItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class EoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FjItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FilItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GaaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class ElItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HawItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IwItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HmnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class I(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IdItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ItItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class JaOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class JaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class JvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KhaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RwItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KriItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LuaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LuoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LbItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class M(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MfeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NewItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NsoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class OcItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class OrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class OmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class O(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PamItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class P(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtPtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class QuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GdItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class Cr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SdItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class StItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class E(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SwItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class S(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ThItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ToItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class T(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TumItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UzItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class VeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ViItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class WarItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class WoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class XhItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class YiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class YoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AutomaticCaptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ab: list[AbItem] | None = None
    aa: list[AaItem] | None = None
    af: list[AfItem] | None = None
    ak: list[AkItem] | None = None
    sq: list[SqItem] | None = None
    am: list[AmItem] | None = None
    ar: list[ArItem] | None = None
    hy: list[HyItem] | None = None
    as_: list[A] | None = Field(None, alias="as")
    ay: list[AyItem] | None = None
    az: list[AzItem] | None = None
    bn: list[BnItem] | None = None
    ba: list[BaItem] | None = None
    eu: list[EuItem] | None = None
    be: list[BeItem] | None = None
    bho: list[BhoItem] | None = None
    bs: list[B] | None = None
    br: list[BrItem] | None = None
    bg: list[BgItem] | None = None
    my: list[MyItem] | None = None
    ca: list[CaItem] | None = None
    ceb: list[CebItem] | None = None
    zh_hans: list[ZhHan] | None = Field(None, alias="zh-Hans")
    zh_hant: list[ZhHantItem] | None = Field(None, alias="zh-Hant")
    co: list[CoItem] | None = None
    hr: list[HrItem] | None = None
    cs: list[C] | None = None
    da: list[DaItem] | None = None
    dv: list[DvItem] | None = None
    nl: list[NlItem] | None = None
    dz: list[DzItem] | None = None
    en: list[EnItem]
    eo: list[EoItem] | None = None
    et: list[EtItem] | None = None
    ee: list[EeItem] | None = None
    fo: list[FoItem] | None = None
    fj: list[FjItem] | None = None
    fil: list[FilItem] | None = None
    fi: list[FiItem] | None = None
    fr: list[FrItem] | None = None
    gaa: list[GaaItem] | None = None
    gl: list[GlItem] | None = None
    lg: list[LgItem] | None = None
    ka: list[KaItem] | None = None
    de: list[DeItem]
    el: list[ElItem] | None = None
    gn: list[GnItem] | None = None
    gu: list[GuItem] | None = None
    ht: list[HtItem] | None = None
    ha: list[HaItem] | None = None
    haw: list[HawItem] | None = None
    iw: list[IwItem] | None = None
    hi: list[HiItem] | None = None
    hmn: list[HmnItem] | None = None
    hu: list[HuItem] | None = None
    is_: list[I] | None = Field(None, alias="is")
    ig: list[IgItem] | None = None
    id: list[IdItem] | None = None
    iu: list[IuItem] | None = None
    ga: list[GaItem] | None = None
    it: list[ItItem] | None = None
    ja_orig: list[JaOrigItem] | None = Field(None, alias="ja-orig")
    ja: list[JaItem] | None = None
    jv: list[JvItem] | None = None
    kl: list[KlItem] | None = None
    kn: list[KnItem] | None = None
    kk: list[KkItem] | None = None
    kha: list[KhaItem] | None = None
    km: list[KmItem] | None = None
    rw: list[RwItem] | None = None
    ko: list[KoItem] | None = None
    kri: list[KriItem] | None = None
    ku: list[KuItem] | None = None
    ky: list[KyItem] | None = None
    lo: list[LoItem] | None = None
    la: list[LaItem] | None = None
    lv: list[LvItem] | None = None
    ln: list[LnItem] | None = None
    lt: list[LtItem] | None = None
    lua: list[LuaItem] | None = None
    luo: list[LuoItem] | None = None
    lb: list[LbItem] | None = None
    mk: list[MkItem] | None = None
    mg: list[MgItem] | None = None
    ms: list[M] | None = None
    ml: list[MlItem] | None = None
    mt: list[MtItem] | None = None
    gv: list[GvItem] | None = None
    mi: list[MiItem] | None = None
    mr: list[MrItem] | None = None
    mn: list[MnItem] | None = None
    mfe: list[MfeItem] | None = None
    ne: list[NeItem] | None = None
    new: list[NewItem] | None = None
    nso: list[NsoItem] | None = None
    no: list[NoItem] | None = None
    ny: list[NyItem] | None = None
    oc: list[OcItem] | None = None
    or_: list[OrItem] | None = Field(None, alias="or")
    om: list[OmItem] | None = None
    os: list[O] | None = None
    pam: list[PamItem] | None = None
    ps: list[P] | None = None
    fa: list[FaItem] | None = None
    pl: list[PlItem] | None = None
    pt: list[PtItem] | None = None
    pt_pt: list[PtPtItem] | None = Field(None, alias="pt-PT")
    pa: list[PaItem] | None = None
    qu: list[QuItem] | None = None
    ro: list[RoItem] | None = None
    rn: list[RnItem] | None = None
    ru: list[RuItem] | None = None
    sm: list[SmItem] | None = None
    sg: list[SgItem] | None = None
    sa: list[SaItem] | None = None
    gd: list[GdItem] | None = None
    sr: list[SrItem] | None = None
    crs: list[Cr] | None = None
    sn: list[SnItem] | None = None
    sd: list[SdItem] | None = None
    si: list[SiItem] | None = None
    sk: list[SkItem] | None = None
    sl: list[SlItem] | None = None
    so: list[SoItem] | None = None
    st: list[StItem] | None = None
    es: list[E] | None = None
    su: list[SuItem] | None = None
    sw: list[SwItem] | None = None
    ss: list[S] | None = None
    sv: list[SvItem] | None = None
    tg: list[TgItem] | None = None
    ta: list[TaItem] | None = None
    tt: list[TtItem] | None = None
    te: list[TeItem] | None = None
    th: list[ThItem] | None = None
    bo: list[BoItem] | None = None
    ti: list[TiItem] | None = None
    to: list[ToItem] | None = None
    ts: list[T] | None = None
    tn: list[TnItem] | None = None
    tum: list[TumItem] | None = None
    tr: list[TrItem] | None = None
    tk: list[TkItem] | None = None
    uk: list[UkItem] | None = None
    ur: list[UrItem] | None = None
    ug: list[UgItem] | None = None
    uz: list[UzItem] | None = None
    ve: list[VeItem] | None = None
    vi: list[ViItem] | None = None
    war: list[WarItem] | None = None
    cy: list[CyItem] | None = None
    fy: list[FyItem] | None = None
    wo: list[WoItem] | None = None
    xh: list[XhItem] | None = None
    yi: list[YiItem] | None = None
    yo: list[YoItem] | None = None
    zu: list[ZuItem] | None = None


class EnItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class Subtitles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: list[EnItem1] | None = None
    de: list[DeItem1] | None = None


class Chapter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_time: float
    title: str


class HeatmapItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_time: float
    end_time: float
    value: float


class FieldVersion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    version: str
    current_git_head: None
    release_git_head: str
    repository: str


class Model(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    title: str
    formats: list[Format]
    thumbnails: list[Thumbnail]
    thumbnail: str
    description: str
    channel_id: str
    channel_url: str
    duration: int
    view_count: int
    average_rating: None
    age_limit: int
    webpage_url: str
    categories: list[str]
    tags: list[str]
    playable_in_embed: bool
    live_status: str
    media_type: str
    release_timestamp: None
    field_format_sort_fields: list[str] = Field(..., alias="_format_sort_fields")
    automatic_captions: AutomaticCaptions
    subtitles: Subtitles
    comment_count: int
    chapters: list[Chapter] | None = None
    heatmap: list[HeatmapItem] | None = None
    like_count: int
    channel: str
    channel_follower_count: int
    uploader: str
    uploader_id: str
    uploader_url: str
    upload_date: str
    timestamp: int
    availability: str
    field__post_extractor: None = Field(..., alias="__post_extractor")
    original_url: str
    webpage_url_basename: str
    webpage_url_domain: str
    extractor: str
    extractor_key: str
    epoch: int
    field_type: str = Field(..., alias="_type")
    field_version: FieldVersion = Field(..., alias="_version")
    location: str | None = None
    channel_is_verified: bool | None = None
