# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class DownloaderOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    http_chunk_size: int


class HttpHeaders(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user_agent: str = Field(..., alias="User-Agent")
    accept: str = Field(..., alias="Accept")
    accept_language: str = Field(..., alias="Accept-Language")
    sec_fetch_mode: str = Field(..., alias="Sec-Fetch-Mode")


class Format(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asr: int | None = None
    filesize: int | None = None
    format_id: str
    format_note: str | None = None
    source_preference: int
    fps: float | None = None
    audio_channels: int | None = None
    height: int | None = None
    quality: float
    has_drm: bool
    tbr: float
    filesize_approx: int | None = None
    url: str
    width: int | None = None
    language: None = None
    language_preference: int | None = None
    preference: None
    ext: str
    vcodec: str
    acodec: str
    dynamic_range: str | None = None
    container: str | None = None
    available_at: int
    downloader_options: DownloaderOptions | None = None
    protocol: str
    audio_ext: str
    video_ext: str
    vbr: float | None = None
    abr: float | None = None
    resolution: str
    aspect_ratio: float | None = None
    http_headers: HttpHeaders
    format: str
    format_index: None = None
    manifest_url: str | None = None


class Thumbnail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    preference: int
    id: str
    height: int | None = None
    width: int | None = None
    resolution: str | None = None


class EnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AutomaticCaptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: list[EnItem]
    de: list[DeItem]


class EnItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class Subtitles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en: list[EnItem1]
    de: list[DeItem1]


class Chapter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_time: float
    title: str
    end_time: float


class HeatmapItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_time: float
    end_time: float
    value: float


class RequestedFormat(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asr: int | None = None
    filesize: int
    format_id: str
    format_note: str
    source_preference: int
    fps: int | None = None
    audio_channels: int | None = None
    height: int | None = None
    quality: float
    has_drm: bool
    tbr: float
    filesize_approx: int
    url: str
    width: int | None = None
    language: None
    language_preference: int
    preference: None
    ext: str
    vcodec: str
    acodec: str
    dynamic_range: str | None = None
    container: str
    available_at: int
    downloader_options: DownloaderOptions
    protocol: str
    video_ext: str
    audio_ext: str
    abr: float
    vbr: float
    resolution: str
    aspect_ratio: float | None = None
    http_headers: HttpHeaders
    format: str


class FieldVersion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    version: str
    current_git_head: None
    release_git_head: str
    repository: str


class Video(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    title: str
    formats: list[Format]
    thumbnails: list[Thumbnail]
    thumbnail: str
    description: str
    channel_id: str
    channel_url: str
    duration: int
    view_count: int
    average_rating: None
    age_limit: int
    webpage_url: str
    categories: list[str]
    tags: list[str]
    playable_in_embed: bool
    live_status: str
    media_type: str
    release_timestamp: None
    field_format_sort_fields: list[str] = Field(..., alias="_format_sort_fields")
    automatic_captions: AutomaticCaptions
    subtitles: Subtitles
    comment_count: int
    chapters: list[Chapter]
    heatmap: list[HeatmapItem]
    location: str
    like_count: int
    channel: str
    channel_follower_count: int
    channel_is_verified: bool
    uploader: str
    uploader_id: str
    uploader_url: str
    upload_date: str
    timestamp: int
    availability: str
    original_url: str
    webpage_url_basename: str
    webpage_url_domain: str
    extractor: str
    extractor_key: str
    playlist: None
    playlist_index: None
    display_id: str
    fulltitle: str
    duration_string: str
    release_year: None
    is_live: bool
    was_live: bool
    requested_subtitles: None
    field_has_drm: None = Field(..., alias="_has_drm")
    epoch: int
    requested_formats: list[RequestedFormat]
    format: str
    format_id: str
    ext: str
    protocol: str
    language: None
    format_note: str
    filesize_approx: int
    tbr: float
    width: int
    height: int
    resolution: str
    fps: int
    dynamic_range: str
    vcodec: str
    vbr: float
    stretched_ratio: None
    aspect_ratio: float
    acodec: str
    abr: float
    asr: int
    audio_channels: int
    field_type: str = Field(..., alias="_type")
    field_version: FieldVersion = Field(..., alias="_version")
