# generated by datamodel-codegen:
#   filename:  <stdin>

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class DownloaderOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    http_chunk_size: int


class Fragment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    duration: float


class Format(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    asr: int | None = None
    filesize: int | None = None
    format_id: str
    format_note: str | None = None
    source_preference: int | None = None
    fps: float | None = None
    audio_channels: int | None = None
    height: int | None = None
    quality: float | None = None
    has_drm: bool | None = None
    tbr: float | None = None
    filesize_approx: int | None = None
    url: str
    width: int | None = None
    language: str | None = None
    language_preference: int | None = None
    preference: None = None
    ext: str
    vcodec: str
    acodec: str
    dynamic_range: str | None = None
    available_at: int | None = None
    downloader_options: DownloaderOptions | None = None
    container: str | None = None
    format_index: None = None
    manifest_url: str | None = None
    protocol: str | None = None
    rows: int | None = None
    columns: int | None = None
    fragments: list[Fragment] | None = None
    stretched_ratio: float | None = None
    field__needs_testing: bool | None = Field(None, alias="__needs_testing")


class Thumbnail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    height: int | None = None
    width: int | None = None
    preference: int


class AbItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AfItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class AkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SqItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ArItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class HyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class A(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AzItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class BaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BhoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class B(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CebItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhHan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class ZhHantItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class CoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class C(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class DaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class DvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class DzItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class EoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FjItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FilItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class FiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class FrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class GaaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class ElItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class GnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HawItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IwItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class HiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class HmnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class I(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IdOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IdItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class IuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ItItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class JaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class JvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KhaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RwItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class KriItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class LnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class LuaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LuoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LbItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class M(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class MlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class MfeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NewItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NsoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class NyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class OcItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class OrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class OmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class O(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PamItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class P(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class PlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class PtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class PtPtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class PaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class QuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class RnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class SmItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class GdItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class Cr(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SdItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SlItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class StItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class E(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class SuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SwItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class S(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SvItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class TgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TtItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ThItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class BoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ToItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class T(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TumItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class TkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class UrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UgItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UzItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class VeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ViItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str | None = None
    impersonate: bool | None = None
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")
    protocol: str | None = None


class WarItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FyItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class WoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class XhItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class YiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class YoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZuItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtBrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SvOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnCaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnGbItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EsMxItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ThOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class JaOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NlOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ViOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ItOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LvOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TeOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UkOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class CsOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FrCaItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeDeItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HiLatnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EsU(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DaOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class Es419Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TrOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FrOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HuOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SrLatnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PlOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EsOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnU(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BgOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KoOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RoOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FrFrItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ArOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class YueHkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhHkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ElOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NoOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RuOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhCnItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhTwItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UndItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    ext: str
    protocol: str
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HiOrigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AutomaticCaptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ab: list[AbItem] | None = None
    aa: list[AaItem] | None = None
    af: list[AfItem] | None = None
    ak: list[AkItem] | None = None
    sq: list[SqItem] | None = None
    am: list[AmItem] | None = None
    ar: list[ArItem] | None = None
    hy: list[HyItem] | None = None
    as_: list[A] | None = Field(None, alias="as")
    ay: list[AyItem] | None = None
    az: list[AzItem] | None = None
    bn: list[BnItem] | None = None
    ba: list[BaItem] | None = None
    eu: list[EuItem] | None = None
    be: list[BeItem] | None = None
    bho: list[BhoItem] | None = None
    bs: list[B] | None = None
    br: list[BrItem] | None = None
    bg: list[BgItem] | None = None
    my: list[MyItem] | None = None
    ca: list[CaItem] | None = None
    ceb: list[CebItem] | None = None
    zh_hans: list[ZhHan] | None = Field(None, alias="zh-Hans")
    zh_hant: list[ZhHantItem] | None = Field(None, alias="zh-Hant")
    co: list[CoItem] | None = None
    hr: list[HrItem] | None = None
    cs: list[C] | None = None
    da: list[DaItem] | None = None
    dv: list[DvItem] | None = None
    nl: list[NlItem] | None = None
    dz: list[DzItem] | None = None
    en: list[EnItem] | None = None
    eo: list[EoItem] | None = None
    et: list[EtItem] | None = None
    ee: list[EeItem] | None = None
    fo: list[FoItem] | None = None
    fj: list[FjItem] | None = None
    fil: list[FilItem] | None = None
    fi: list[FiItem] | None = None
    fr: list[FrItem] | None = None
    gaa: list[GaaItem] | None = None
    gl: list[GlItem] | None = None
    lg: list[LgItem] | None = None
    ka: list[KaItem] | None = None
    de: list[DeItem] | None = None
    el: list[ElItem] | None = None
    gn: list[GnItem] | None = None
    gu: list[GuItem] | None = None
    ht: list[HtItem] | None = None
    ha: list[HaItem] | None = None
    haw: list[HawItem] | None = None
    iw: list[IwItem] | None = None
    hi: list[HiItem] | None = None
    hmn: list[HmnItem] | None = None
    hu: list[HuItem] | None = None
    is_: list[I] | None = Field(None, alias="is")
    ig: list[IgItem] | None = None
    id_orig: list[IdOrigItem] | None = Field(None, alias="id-orig")
    id: list[IdItem] | None = None
    iu: list[IuItem] | None = None
    ga: list[GaItem] | None = None
    it: list[ItItem] | None = None
    ja: list[JaItem] | None = None
    jv: list[JvItem] | None = None
    kl: list[KlItem] | None = None
    kn: list[KnItem] | None = None
    kk: list[KkItem] | None = None
    kha: list[KhaItem] | None = None
    km: list[KmItem] | None = None
    rw: list[RwItem] | None = None
    ko: list[KoItem] | None = None
    kri: list[KriItem] | None = None
    ku: list[KuItem] | None = None
    ky: list[KyItem] | None = None
    lo: list[LoItem] | None = None
    la: list[LaItem] | None = None
    lv: list[LvItem] | None = None
    ln: list[LnItem] | None = None
    lt: list[LtItem] | None = None
    lua: list[LuaItem] | None = None
    luo: list[LuoItem] | None = None
    lb: list[LbItem] | None = None
    mk: list[MkItem] | None = None
    mg: list[MgItem] | None = None
    ms: list[M] | None = None
    ml: list[MlItem] | None = None
    mt: list[MtItem] | None = None
    gv: list[GvItem] | None = None
    mi: list[MiItem] | None = None
    mr: list[MrItem] | None = None
    mn: list[MnItem] | None = None
    mfe: list[MfeItem] | None = None
    ne: list[NeItem] | None = None
    new: list[NewItem] | None = None
    nso: list[NsoItem] | None = None
    no: list[NoItem] | None = None
    ny: list[NyItem] | None = None
    oc: list[OcItem] | None = None
    or_: list[OrItem] | None = Field(None, alias="or")
    om: list[OmItem] | None = None
    os: list[O] | None = None
    pam: list[PamItem] | None = None
    ps: list[P] | None = None
    fa: list[FaItem] | None = None
    pl: list[PlItem] | None = None
    pt: list[PtItem] | None = None
    pt_pt: list[PtPtItem] | None = Field(None, alias="pt-PT")
    pa: list[PaItem] | None = None
    qu: list[QuItem] | None = None
    ro: list[RoItem] | None = None
    rn: list[RnItem] | None = None
    ru: list[RuItem] | None = None
    sm: list[SmItem] | None = None
    sg: list[SgItem] | None = None
    sa: list[SaItem] | None = None
    gd: list[GdItem] | None = None
    sr: list[SrItem] | None = None
    crs: list[Cr] | None = None
    sn: list[SnItem] | None = None
    sd: list[SdItem] | None = None
    si: list[SiItem] | None = None
    sk: list[SkItem] | None = None
    sl: list[SlItem] | None = None
    so: list[SoItem] | None = None
    st: list[StItem] | None = None
    es: list[E] | None = None
    su: list[SuItem] | None = None
    sw: list[SwItem] | None = None
    ss: list[S] | None = None
    sv: list[SvItem] | None = None
    tg: list[TgItem] | None = None
    ta: list[TaItem] | None = None
    tt: list[TtItem] | None = None
    te: list[TeItem] | None = None
    th: list[ThItem] | None = None
    bo: list[BoItem] | None = None
    ti: list[TiItem] | None = None
    to: list[ToItem] | None = None
    ts: list[T] | None = None
    tn: list[TnItem] | None = None
    tum: list[TumItem] | None = None
    tr: list[TrItem] | None = None
    tk: list[TkItem] | None = None
    uk: list[UkItem] | None = None
    ur: list[UrItem] | None = None
    ug: list[UgItem] | None = None
    uz: list[UzItem] | None = None
    ve: list[VeItem] | None = None
    vi: list[ViItem] | None = None
    war: list[WarItem] | None = None
    cy: list[CyItem] | None = None
    fy: list[FyItem] | None = None
    wo: list[WoItem] | None = None
    xh: list[XhItem] | None = None
    yi: list[YiItem] | None = None
    yo: list[YoItem] | None = None
    zu: list[ZuItem] | None = None
    pt_br: list[PtBrItem] | None = Field(None, alias="pt-BR")
    en_orig: list[EnOrigItem] | None = Field(None, alias="en-orig")
    sv_orig: list[SvOrigItem] | None = Field(None, alias="sv-orig")
    pt_orig: list[PtOrigItem] | None = Field(None, alias="pt-orig")
    en_ca: list[EnCaItem] | None = Field(None, alias="en-CA")
    en_gb: list[EnGbItem] | None = Field(None, alias="en-GB")
    es_mx: list[EsMxItem] | None = Field(None, alias="es-MX")
    th_orig: list[ThOrigItem] | None = Field(None, alias="th-orig")
    ja_orig: list[JaOrigItem] | None = Field(None, alias="ja-orig")
    nl_orig: list[NlOrigItem] | None = Field(None, alias="nl-orig")
    vi_orig: list[ViOrigItem] | None = Field(None, alias="vi-orig")
    it_orig: list[ItOrigItem] | None = Field(None, alias="it-orig")
    lv_orig: list[LvOrigItem] | None = Field(None, alias="lv-orig")
    te_orig: list[TeOrigItem] | None = Field(None, alias="te-orig")
    uk_orig: list[UkOrigItem] | None = Field(None, alias="uk-orig")
    cs_orig: list[CsOrigItem] | None = Field(None, alias="cs-orig")
    zh: list[ZhItem] | None = None
    fr_ca: list[FrCaItem] | None = Field(None, alias="fr-CA")
    de_de: list[DeDeItem] | None = Field(None, alias="de-DE")
    hi_latn: list[HiLatnItem] | None = Field(None, alias="hi-Latn")
    es_us: list[EsU] | None = Field(None, alias="es-US")
    da_orig: list[DaOrigItem] | None = Field(None, alias="da-orig")
    es_419: list[Es419Item] | None = Field(None, alias="es-419")
    tr_orig: list[TrOrigItem] | None = Field(None, alias="tr-orig")
    fr_orig: list[FrOrigItem] | None = Field(None, alias="fr-orig")
    hu_orig: list[HuOrigItem] | None = Field(None, alias="hu-orig")
    sr_latn: list[SrLatnItem] | None = Field(None, alias="sr-Latn")
    pl_orig: list[PlOrigItem] | None = Field(None, alias="pl-orig")
    es_orig: list[EsOrigItem] | None = Field(None, alias="es-orig")
    en_us: list[EnU] | None = Field(None, alias="en-US")
    bg_orig: list[BgOrigItem] | None = Field(None, alias="bg-orig")
    ko_orig: list[KoOrigItem] | None = Field(None, alias="ko-orig")
    ro_orig: list[RoOrigItem] | None = Field(None, alias="ro-orig")
    fr_fr: list[FrFrItem] | None = Field(None, alias="fr-FR")
    de_orig: list[DeOrigItem] | None = Field(None, alias="de-orig")
    ar_orig: list[ArOrigItem] | None = Field(None, alias="ar-orig")
    yue_hk: list[YueHkItem] | None = Field(None, alias="yue-HK")
    zh_hk: list[ZhHkItem] | None = Field(None, alias="zh-HK")
    el_orig: list[ElOrigItem] | None = Field(None, alias="el-orig")
    no_orig: list[NoOrigItem] | None = Field(None, alias="no-orig")
    ru_orig: list[RuOrigItem] | None = Field(None, alias="ru-orig")
    zh_cn: list[ZhCnItem] | None = Field(None, alias="zh-CN")
    zh_tw: list[ZhTwItem] | None = Field(None, alias="zh-TW")
    und: list[UndItem] | None = None
    hi_orig: list[HiOrigItem] | None = Field(None, alias="hi-orig")


class EnXp8wTkmrYBkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtBrJspEhZvLOItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnNDZxDvBzfQItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnPouLeejqa6oItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LiveChatItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    url: str
    video_id: str
    ext: str
    protocol: str


class EnCaItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class En9eiXt6ySmEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HrItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NlItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnGbItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FrItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ElItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IdItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class M1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class NoItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FaItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PlItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EsMxItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SvItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnJ0xToLx3gb0Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhHan1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class C1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FiItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class IwItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HuItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ItItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class JaItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class KoItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtBrItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtPtItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnSuLrHg0Xb(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnKJvOv4rEmM(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class E1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FilItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FrCaItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeDeItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HiLatnItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EsU1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnS3doMv87xA4Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ArItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class BnItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhHantItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class HiItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RuItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ThItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class TrItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ViItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnAwfepn8fFiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnP4i0xssmYcEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnYr9pFrNQcaAItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class Es419Item1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnYpJ3S0Bj5AItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnCb86G5bK7IItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnWpVrXuwcxxcItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnTf0V9a3vshAItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class En5ygCYqaDmLkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SrLatnItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DaItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class SwItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnPI4Zk2NlIItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnTOzlBsTRuoItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnU1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnEhkg1hFWq8AItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LvItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnH0r5K7l4WNkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnS2gbU5ljcq4Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class PtBrMoMsfEz0NOkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnQFyOiwBq10Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class FrFrItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class YueHkItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhHkItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnVcGHmSWTfEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class En8Lfr7GhEJaEItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnJD0Iv6GkiD(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnRte56yurQ6AItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class En2bOm3bHb6WiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnYgLBeh9fEk0Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class LtItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UkItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class En1UPqh9hJnliItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnBm5HrZbHsWkItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class AfItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class DeEhkg1hFWq8AItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhCnItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class ZhTwItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class RoItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class UndItem1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnOHufOlTIizMItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class EnYnQ5YrSllPiItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ext: str
    url: str
    name: str
    impersonate: bool
    field__yt_dlp_client: str = Field(..., alias="__yt_dlp_client")


class Subtitles(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    en_xp8w_tkmr_y_bk: list[EnXp8wTkmrYBkItem] | None = Field(
        None,
        alias="en-xp8wTkmrYBk",
    )
    pt_br_jsp_eh_zv_l__o: list[PtBrJspEhZvLOItem] | None = Field(
        None,
        alias="pt-BR-jspEhZvL__o",
    )
    en_n_d_zx_dv_bzf_q: list[EnNDZxDvBzfQItem] | None = Field(
        None,
        alias="en-nDZxDv-bzfQ",
    )
    en_pou_leejqa6o: list[EnPouLeejqa6oItem] | None = Field(
        None,
        alias="en-PouLeejqa6o",
    )
    live_chat: list[LiveChatItem] | None = None
    en_ca: list[EnCaItem1] | None = Field(None, alias="en-CA")
    en_9ei_xt6y_sm_e: list[En9eiXt6ySmEItem] | None = Field(
        None,
        alias="en-9eiXt6y-smE",
    )
    hr: list[HrItem1] | None = None
    nl: list[NlItem1] | None = None
    en_gb: list[EnGbItem1] | None = Field(None, alias="en-GB")
    fr: list[FrItem1] | None = None
    el: list[ElItem1] | None = None
    id: list[IdItem1] | None = None
    ms: list[M1] | None = None
    no: list[NoItem1] | None = None
    fa: list[FaItem1] | None = None
    pl: list[PlItem1] | None = None
    pt: list[PtItem1] | None = None
    es_mx: list[EsMxItem1] | None = Field(None, alias="es-MX")
    sv: list[SvItem1] | None = None
    en_j0x_to_lx3gb0: list[EnJ0xToLx3gb0Item] | None = Field(
        None,
        alias="en-j0xToLx3gb0",
    )
    zh_hans: list[ZhHan1] | None = Field(None, alias="zh-Hans")
    cs: list[C1] | None = None
    en: list[EnItem1] | None = None
    fi: list[FiItem1] | None = None
    de: list[DeItem1] | None = None
    iw: list[IwItem1] | None = None
    hu: list[HuItem1] | None = None
    it: list[ItItem1] | None = None
    ja: list[JaItem1] | None = None
    ko: list[KoItem1] | None = None
    pt_br: list[PtBrItem1] | None = Field(None, alias="pt-BR")
    pt_pt: list[PtPtItem1] | None = Field(None, alias="pt-PT")
    en_su_lr_hg0_xbs: list[EnSuLrHg0Xb] | None = Field(None, alias="en-Su_lrHG0Xbs")
    en_k_jv_ov4r_em_ms: list[EnKJvOv4rEmM] | None = Field(
        None,
        alias="en-kJvOV4rEMMs",
    )
    zh: list[ZhItem1] | None = None
    es: list[E1] | None = None
    fil: list[FilItem1] | None = None
    fr_ca: list[FrCaItem1] | None = Field(None, alias="fr-CA")
    de_de: list[DeDeItem1] | None = Field(None, alias="de-DE")
    hi_latn: list[HiLatnItem1] | None = Field(None, alias="hi-Latn")
    es_us: list[EsU1] | None = Field(None, alias="es-US")
    en_s3do_mv87x_a4: list[EnS3doMv87xA4Item] | None = Field(
        None,
        alias="en-S3doMV87xA4",
    )
    ar: list[ArItem1] | None = None
    bn: list[BnItem1] | None = None
    zh_hant: list[ZhHantItem1] | None = Field(None, alias="zh-Hant")
    hi: list[HiItem1] | None = None
    ru: list[RuItem1] | None = None
    th: list[ThItem1] | None = None
    tr: list[TrItem1] | None = None
    vi: list[ViItem1] | None = None
    en_awfepn8f_fi: list[EnAwfepn8fFiItem] | None = Field(
        None,
        alias="en-Awfepn8f_FI",
    )
    en_p4i0xssm_yc_e: list[EnP4i0xssmYcEItem] | None = Field(
        None,
        alias="en-p4i0xssmYcE",
    )
    en_yr9p_fr_n_qca_a: list[EnYr9pFrNQcaAItem] | None = Field(
        None,
        alias="en-YR9pFrNQcaA",
    )
    es_419: list[Es419Item1] | None = Field(None, alias="es-419")
    en_yp_j3_s0_bj5_a: list[EnYpJ3S0Bj5AItem] | None = Field(
        None,
        alias="en-ypJ3S0_BJ5A",
    )
    en_cb86_g5b_k_7_i: list[EnCb86G5bK7IItem] | None = Field(
        None,
        alias="en-cb86G5bK_7I",
    )
    en_wp_vr_xuwcxxc: list[EnWpVrXuwcxxcItem] | None = Field(
        None,
        alias="en-wpVRXuwcxxc",
    )
    en_tf0_v9a3vsh_a: list[EnTf0V9a3vshAItem] | None = Field(
        None,
        alias="en-Tf0V9a3vshA",
    )
    en_5yg_c_yqa_dm_lk: list[En5ygCYqaDmLkItem] | None = Field(
        None,
        alias="en-5ygCYqaDmLk",
    )
    sr_latn: list[SrLatnItem1] | None = Field(None, alias="sr-Latn")
    da: list[DaItem1] | None = None
    sw: list[SwItem1] | None = None
    en_p_i_4_zk2_nl_i: list[EnPI4Zk2NlIItem] | None = Field(
        None,
        alias="en-pI-4Zk2Nl-I",
    )
    en_t_ozl_bs_t_ruo: list[EnTOzlBsTRuoItem] | None = Field(
        None,
        alias="en-T-OzlBsTRuo",
    )
    en_us: list[EnU1] | None = Field(None, alias="en-US")
    en_ehkg1h_f_wq8_a: list[EnEhkg1hFWq8AItem] | None = Field(
        None,
        alias="en-ehkg1hFWq8A",
    )
    lv: list[LvItem1] | None = None
    en_h0r5_k7l4_w_nk: list[EnH0r5K7l4WNkItem] | None = Field(
        None,
        alias="en-H0r5K7l4WNk",
    )
    en_s2gb_u5ljcq4: list[EnS2gbU5ljcq4Item] | None = Field(
        None,
        alias="en-s2gbU5ljcq4",
    )
    pt_br_mo_msf_ez0_n_ok: list[PtBrMoMsfEz0NOkItem] | None = Field(
        None,
        alias="pt-BR-MOMsfEz0NOk",
    )
    en_q_fy_oiw_bq10: list[EnQFyOiwBq10Item] | None = Field(
        None,
        alias="en-QFy_OIWBq10",
    )
    fr_fr: list[FrFrItem1] | None = Field(None, alias="fr-FR")
    yue_hk: list[YueHkItem1] | None = Field(None, alias="yue-HK")
    zh_hk: list[ZhHkItem1] | None = Field(None, alias="zh-HK")
    en_vc_g_hm_s_w_tf_e: list[EnVcGHmSWTfEItem] | None = Field(
        None,
        alias="en-vcGHm_sWTfE",
    )
    en_8_lfr7_gh_e_ja_e: list[En8Lfr7GhEJaEItem] | None = Field(
        None,
        alias="en-8LFR7GhEJaE",
    )
    en_j_d0_iv6_gki_ds: list[EnJD0Iv6GkiD] | None = Field(
        None,
        alias="en-jD0Iv6GKIDs",
    )
    en_rte56yur_q6_a: list[EnRte56yurQ6AItem] | None = Field(
        None,
        alias="en-rte56yurQ6A",
    )
    en_2b_om3b_hb6_wi: list[En2bOm3bHb6WiItem] | None = Field(
        None,
        alias="en-2bOm3bHB6WI",
    )
    en_yg_l_beh9f_ek0: list[EnYgLBeh9fEk0Item] | None = Field(
        None,
        alias="en-YgLBeh9fEK0",
    )
    lt: list[LtItem1] | None = None
    uk: list[UkItem1] | None = None
    en_1_u_pqh9h_jnli: list[En1UPqh9hJnliItem] | None = Field(
        None,
        alias="en-1UPqh9hJNLI",
    )
    en_bm5_hr_zb_hs_wk: list[EnBm5HrZbHsWkItem] | None = Field(
        None,
        alias="en-bm5HrZbHsWk",
    )
    af: list[AfItem1] | None = None
    de_ehkg1h_f_wq8_a: list[DeEhkg1hFWq8AItem] | None = Field(
        None,
        alias="de-ehkg1hFWq8A",
    )
    zh_cn: list[ZhCnItem1] | None = Field(None, alias="zh-CN")
    zh_tw: list[ZhTwItem1] | None = Field(None, alias="zh-TW")
    ro: list[RoItem1] | None = None
    und: list[UndItem1] | None = None
    en_o_huf_ol_t_iiz_m: list[EnOHufOlTIizMItem] | None = Field(
        None,
        alias="en-oHUFOlTIizM",
    )
    en_yn_q5_yr_sll_pi: list[EnYnQ5YrSllPiItem] | None = Field(
        None,
        alias="en-ynQ5YRSllPI",
    )


class Chapter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_time: float
    title: str


class HeatmapItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    start_time: float
    end_time: float
    value: float


class FieldVersion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    version: str
    current_git_head: None
    release_git_head: str
    repository: str


class Video(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    title: str
    formats: list[Format]
    thumbnails: list[Thumbnail]
    thumbnail: str
    description: str
    channel_id: str
    channel_url: str
    duration: int | None = None
    view_count: int
    average_rating: None
    age_limit: int
    webpage_url: str
    categories: list[str]
    tags: list[str]
    playable_in_embed: bool
    live_status: str
    media_type: str
    release_timestamp: int | None = None
    field_format_sort_fields: list[str] = Field(..., alias="_format_sort_fields")
    automatic_captions: AutomaticCaptions
    subtitles: Subtitles
    comment_count: int | None = None
    chapters: list[Chapter] | None = None
    heatmap: list[HeatmapItem] | None = None
    like_count: int | None = None
    channel: str | None = None
    channel_follower_count: int | None = None
    channel_is_verified: bool | None = None
    uploader: str | None = None
    uploader_id: str | None = None
    uploader_url: str | None = None
    upload_date: str
    timestamp: int
    availability: str
    field__post_extractor: None = Field(..., alias="__post_extractor")
    original_url: str
    webpage_url_basename: str
    webpage_url_domain: str
    extractor: str
    extractor_key: str
    epoch: int
    field_type: str = Field(..., alias="_type")
    field_version: FieldVersion = Field(..., alias="_version")
    license: str | None = None
    location: str | None = None
    concurrent_view_count: int | None = None
    album: str | None = None
    artists: list[str] | None = None
    track: str | None = None
    release_date: str | None = None
    release_year: int | None = None
    creators: list[str] | None = None
    alt_title: str | None = None
